### PR TITLE
Add instance variable which holds line in which errors happen

### PR DESCRIPTION
**Pull request by santilytics**
This PR simply adds the Line number as an instance variable. The test coverage piggy backs from existing tests to show the line numbers are correct.
Using a set ensures no line errors are repeated even if multiple validators find errors in the same line.

Would you like to add the line number to the error log? If so, where do you consider is the best place to be added if at all?

### CODE REVIEW

**Comment by di** [comment]
Hi! Thanks for the PR. Looks like the Travis CI integration no longer works, would you be able to resolve #75?

**Comment by santilytics** [comment]
I don't believe I have the permissions to do so and I haven't used github actions before but I could give it a try

**Comment by di** [comment]
Let's keep these as separate PRs

**Comment by di** [comment]
@santilytics Thanks! Released in https://pypi.org/project/vladiate/0.0.24/

**Pull request merged**
