### PR TITLE
Pipe additional args to LocalFile.open()

### PR DESCRIPTION
**Pull request by cal97g**
Allows users to specify encoding, error behaviour etc
https://docs.python.org/3/library/functions.html#open

### CODE REVIEW

**Comment by cal97g** [comment]
It could be argued that in this instance users should create their own subclass of `VladInput` to handle issues like this; however it seems pretty unobtrusive to pipe the kwargs directly to open.

Let me know if maintainers would like this or would like users to just subclass. I can get the final stage to pass.

**Comment by di** [comment]
Just curious, what parameters are you needing to pass here?

**Comment by cal97g** [comment]
@di 
Due to circumstances outside of my control I'm having to deal with files with incorrect / bad encoding. I'd like to specify an encoding and ignore any errors that occur after that!

Basically, Vladiate tries to validate my dodgy CSV but can't due to the above. By passing some params into `open` we can mitigate this somewhat.

```
Traceback (most recent call last):
File "ui.py", line 39, in <module>
ui()
File "site-packages\gooey\python_bindings\gooey_decorator.py", line 89, in <lambda>
File "ui.py", line 33, in ui
somevar=True,
File "main.py", line 32, in main
apps_location=applications_file
File "core\validate.py", line 42, in applications_file
passed = validator.validate()
File "site-packages\vladiate\vlad.py", line 80, in validate
File "site-packages\vladiate\inputs.py", line 35, in open
File "c:\users\callam\appdata\local\programs\python\python36\lib\encodings\cp1252.py", line 23,
in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 6956: character maps to
<undefined>
```

**Comment by di** [comment]
Got it, thanks. I think the "right" thing to do here would be to just subclass `LocalFile`. I don't think it's very intuitive to pass all the kwargs along like that, and it would make it challenging for us to add any kwargs that aren't passed along (i.e., would be used in the constructor) in the future.

**Comment by cal97g** [comment]
Agree, that is cleaner. Thanks! @di

**Pull request closed without merging**
